/** Traduction des noms de pays (anglais → français) */
export const COUNTRY_FR: Record<string, string> = {
  Algeria:                  'Algérie',
  Argentina:                'Argentine',
  Australia:                'Australie',
  Austria:                  'Autriche',
  Belgium:                  'Belgique',
  'Bosnia and Herzegovina': 'Bosnie-Herzégovine',
  Brazil:                   'Brésil',
  Canada:                   'Canada',
  'Cape Verde':             'Cap-Vert',
  Colombia:                 'Colombie',
  'Congo DR':               'Congo RD',
  Croatia:                  'Croatie',
  'Curaçao':                'Curaçao',
  Czechia:                  'Tchéquie',
  Ecuador:                  'Équateur',
  Egypt:                    'Égypte',
  England:                  'Angleterre',
  France:                   'France',
  Germany:                  'Allemagne',
  Ghana:                    'Ghana',
  Haiti:                    'Haïti',
  Iran:                     'Iran',
  Iraq:                     'Irak',
  'Ivory Coast':            "Côte d'Ivoire",
  Japan:                    'Japon',
  Jordan:                   'Jordanie',
  Mexico:                   'Mexique',
  Morocco:                  'Maroc',
  Netherlands:              'Pays-Bas',
  'New Zealand':            'Nouvelle-Zélande',
  Norway:                   'Norvège',
  Panama:                   'Panama',
  Paraguay:                 'Paraguay',
  Portugal:                 'Portugal',
  Qatar:                    'Qatar',
  'Saudi Arabia':           'Arabie Saoudite',
  Scotland:                 'Écosse',
  Senegal:                  'Sénégal',
  'South Africa':           'Afrique du Sud',
  'South Korea':            'Corée du Sud',
  Spain:                    'Espagne',
  Sweden:                   'Suède',
  Switzerland:              'Suisse',
  Tunisia:                  'Tunisie',
  'Türkiye':                'Turquie',
  USA:                      'États-Unis',
  Uruguay:                  'Uruguay',
  Uzbekistan:               'Ouzbékistan',
}

export function countryFR(name: string): string {
  return COUNTRY_FR[name] ?? name
}
